CREATE TABLE IF NOT EXISTS ivasskin(
User TEXT NOT NULL,
Password TEXT NOT NULL,
id INTEGER PRIMARY KEY AUTOINCREMENT,
url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
text TEXT NOT NULL,
time INTEGER NOT NULL
);