# Generated by Django 5.2.4 on 2025-07-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='ivaapp/images/'),
        ),
    ]
