# Generated by Django 5.2.4 on 2025-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaapp', '0003_alter_app_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='', verbose_name='ivaapp/images/')),
            ],
        ),
    ]
