# Generated by Django 5.2.4 on 2025-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaapp', '0004_forclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='forclient',
            name='dopinfo1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='forclient',
            name='dopinfo2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='forclient',
            name='dopinfo3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='forclient',
            name='dopinfo4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
