# Generated by Django 5.2.4 on 2025-07-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivaapp', '0005_forclient_dopinfo1_forclient_dopinfo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forclient',
            name='dopinfo1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forclient',
            name='dopinfo2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forclient',
            name='dopinfo3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='forclient',
            name='dopinfo4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
